---
  name: rss bot
  on:
    schedule:
      - cron: '0 05 * * *' # The workflow runs every day at 05:00 am UTC time.
    push:
      branches:
        - master
    workflow_dispatch:
  jobs:
    check-if-deployment-branch-exists:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12.0'
        - name: Cache pip and downloaded packages
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/pip
              ~/.local/lib/python3.12.0/site-packages # Adjust the Python version here
            key: ${{ runner.os }}-pip-${{ hashFiles('app.py') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Setup python and pip
          uses: actions/setup-python@v4
          with:
            python-version: "3.12.0"
            cache: "pip"
        - name: Install required modules from requirements.txt
          run: |
            # Installing required modules
            python -m pip install --upgrade pip
            pip install feedparser tweepy python-dotenv newspaper3k beautifulsoup4
        - name: Provide env variables and run the script
          id: run-python-file
          run: python app.py
          env:
            Bearer_Token: ${{ secrets.Bearer_Token }}
            API_Key: ${{ secrets.API_KEY }}
            API_Key_Secret: ${{ secrets.API_Key_Secret }}
            Access_Token: ${{ secrets.Access_Token }}
            Access_Token_Secret: ${{ secrets.Access_Token_Secret }}
        - name: Commit config.json to default repo if it has changed
          if: steps.run-python-file.outputs.changed_config == 'true'
          run: |
            git checkout ${{ github.ref_name }}
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add config.json
            git commit -m "Commiting config.json due to changes made by script at $(TZ=":Asia/Calcutta" date +"%d/%m/%y %r") IST"
        - name: Commit changes in the deployment branch
          run: |
            # Adds all changes, commits and pushes
            git checkout deployment
            git add --all -- :!requirements.txt :!config.json :!default-config.json :!app.py
            git commit -m "Run workflow at $(TZ=":Asia/Calcutta" date +"%d/%m/%y %r") IST"
            git push origin deployment
